#!/bin/sh
set -eu
case "${1:-}" in
    submit|status) ;;
    *) echo 'Only submit and status are available to the deployment user' >&2; exit 1 ;;
esac
exec /usr/bin/env -i PATH=/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/python3 -I /usr/local/lib/quizzence-release/helper.py "$@"
